language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t udbhav/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true udbhav/react-test npm run test

after_success:
  # name = "<docker username>/<docker image name>" else push is not allowed
  - docker build -t udbhavsomani/prod-client ./client
  - docker build -t udbhavsomani/prod-worker ./worker
  - docker build -t udbhavsomani/prod-server ./server
  - docker build -t udbhavsomani/prod-nginx ./nginx
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to Docker Hub
  - docker push udbhavsomani/prod-client
  - docker push udbhavsomani/prod-worker
  - docker push udbhavsomani/prod-server
  - docker push udbhavsomani/prod-nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-container-docker'
  env: 'Multicontainerdocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-650941031585'
  bucket_path: 'multi-container-docker'
  on:
    branch: complex-prod
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY